version: '2'

networks:
  default:
    external:
      name: ${COMPOSE_PROJECT_NAME} 

services:
  mariadb:
    image: mariadb/columnstore
    container_name: mariadb
    volumes:
      - ./data/:/usr/local/mariadb/columnstore/mysql/db
    environment:
       - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
       - MARIADB_DATABASE=${MARIADB_DATABASE}
       - MARIADB_USER=${MARIADB_USER}
       - MARIADB_PASSWORD=${MARIADB_PASSWORD}
    ports:
      - ${PORT}:3306
